development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://bffucwqhbehykr:41e19c831d36466bfb3736d351b39fe4132b17cfaeb417b99f9278963d0b700e@ec2-107-20-163-238.compute-1.amazonaws.com:5432/d8q02nk76rohu2
  channel_prefix: bfbikeberlin_production
