# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6bfece5889b3b062868eee5abe5e35b210234881d470ed09eeb9bf8139ff6187c83ac850041d4420e29b0c693b60cef580593cebfe8b976736a20c82f232702a

test:
  secret_key_base: cc27fca76fe6992c36ab93f224e5e93384096050f6d4956f02a9a985f216c08a18221ba63657b2d1aacbfe551f4e3d03273aa4dee37eceaa3ea493fab3dc8453

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
